map_server:
  ros__parameters:
    yaml_filename: "/home/spech/tfm_ws/src/rcauto_sim_pkg/mapas/pau_track/mapa_pau_track.yaml"
    use_sim_time: true

# 2. Localización AMCL
amcl:
  ros__parameters:
    use_sim_time: true
    odom_frame_id: "odom"
    base_frame_id: "body_link"
    global_frame_id: "map"
    scan_topic: "scan"
    update_min_d: 0.2
    update_min_a: 0.5
    particle_filter_implementation: "ndt_localization"

    # Parámetros de inicialización
    minimum_score: 50.0            # umbral mínimo de score para partículas
    initial_pose_topic: "/initialpose"
    global_localization: false     # habilita muestreo amplio al inicio

    # Parámetros del filtro de partículas
    min_particles: 500             # número mínimo de partículas
    max_particles: 2000            # número máximo de partículas
    kld_err: 0.02                  # error permitido (KLD sampling)
    kld_z: 0.99                    # nivel de confianza (KLD sampling)
    update_min_d: 0.2              # distancia mínima para actualización (m)
    update_min_a: 0.2              # ángulo mínimo para actualización (rad)
    resample_interval: 1           # cada cuántas actualizaciones re-muestras

    # Modelo del sensor láser
    laser_model_type: "likelihood_field"
    laser_z_hit: 0.95              # peso componente hit
    laser_sigma_hit: 0.2           # desviación estándar de hit
    laser_z_rand: 0.05             # peso componente rand (ruido aleatorio)
    laser_likelihood_max_dist: 2.0 # distancia máxima para campo de probabilidad

    # Tolerancia de transformaciones
    transform_tolerance: 1.0       # segundos de tolerancia TF

    # Parámetros de recuperación
    recovery_alpha1: 0.2            # ruido rotacional ante fallo de odometría
    recovery_alpha2: 0.2            # ruido rotacional ante fallo de odometría
    recovery_alpha3: 0.2            # ruido translacional ante fallo de odometría
    recovery_alpha4: 0.2            # ruido translacional ante fallo de odometría


# 3. Planner global
planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      allow_unknown: false
      default_tolerance: 0.0

# 4. Controlador MPC (MPPI)
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["RegulatedPurePursuit"]
    RegulatedPurePursuit:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      # --------------------------------------------------
      # Parámetros principales
      lookahead_distance: 0.5        # m, distancia de “mirada”
      min_velocity: 0.1              # m/s, velocidad mínima de seguimiento
      max_velocity: 1.0              # m/s, velocidad máxima de seguimiento
      acc_lim: 0.5                   # m/s², límite de aceleración
      # Tolerancias al alcanzar el goal
      yaw_goal_tolerance: 0.05       # rad
      xy_goal_tolerance: 0.05        # m
      # Ajuste dinámico del lookahead según velocidad
      use_velocity_scaled_lookahead: true

# 5. BT Navigator (comportamientos)
behavior_server:
  ros__parameters:
    use_sim_time: true

    # Plugin de BT Navigator
    plugin_lib_name: "nav2_behavior_tree::BehaviorTreeNavigator"

    # ÁRBOL para FollowPath (toma tu Path pre-generado y lo sigue sin replanificar)
    default_bt_xml_filename: "$(find nav2_bt_navigator)/behavior_trees/follow_point.xml"

    # Persistencia de transforms
    transform_tolerance: 1.0

# 6. Costmaps (global y local)
global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: "map"
    robot_base_frame: "body_link"
    update_frequency: 1.0
    publish_frequency: 0.5
    static_map: true

local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: "odom"
    robot_base_frame: "body_link"
    update_frequency: 5.0
    publish_frequency: 2.0
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05

# 7. Lifecycle Manager para localización
lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - map_server
      - amcl
      
# 8. Lifecycle manager
lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - map_server
      - amcl
      - planner_server
      - controller_server
      - behavior_server