localization_slam:
  ros__parameters:
    # ── NO es necesario ni recomendable en localization ──────────
    #map_start_pose: [-89.3, -3.81, 0.0]
    #map_start_at_dock: true
    use_sim_time: true
    # ── Modos y fuente del mapa ──────────────────────────────────
    mode: localization
    use_map_topic: true   # se suscribe a /map, no crea uno nuevo

    # ── TF frames y tópico de scan ──────────────────────────────
    odom_frame: odom
    map_frame:  map
    base_frame: body_link
    scan_topic: /scan

    # ── Publicación del TF map→odom ─────────────────────────────
    transform_publish_period: 0.02
    transform_tolerance:      0.1

    # ── Filtro y scan-matching ──────────────────────────────────
    use_scan_matching: true
    update_rate:       1.0
    resolution:        0.05
    max_laser_range:   10.0

    # ── Loop closing (puedes dejarlo o desactivarlo) ────────────
    do_loop_closing: true
    loop_search_maximum_distance:    3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine:   0.45